export const DISPATCH_INCREMENT_INIT = "DISPATCH_INCREMENT_INIT";
export const DISPATCH_INCREMENT = "DISPATCH_INCREMENT";
export const DISPATCH_DECREMENT = "DISPATCH_DECREMENT";
export const DISPATCH_INCREMENT_SUCCESS = "DISPATCH_INCREMENT_SUCCESS";
export const DISPATCH_INCREMENT_ERROR = "DISPATCH_INCREMENT_ERROR";
